### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by Cqrlll** [emmaexe/anilist-notifications#1]
Hi please make a video or a indepth guide on how to do it on android like which app to use like full on detailed instruction im having a headache trying to figure this out lol

**Comment by emmaexe** [comment]
This is a server application. It's a node app that you need to constantly have running in the background either on your computer or on an actual server that fetches the notifications from anilist and forwards them to ntfy. To recieve the notifications using ntfy, look at step 1 here: https://docs.ntfy.sh/

**Comment by Cqrlll** [comment]
> This is a server application. It's a node app that you need to constantly have running in the background either on your computer or on an actual server that fetches the notifications from anilist and forwards them to ntfy. To recieve the notifications using ntfy, look at step 1 here: https://docs.ntfy.sh/

Oh, so its not possible to do in an android device alone understandable sorry if id bothered you:))

**Comment by emmaexe** [comment]
It is but you would have to run it constantly in the background and it would probably affect battery life.

If you want to try this you can download [termux](https://termux.dev/en/).
Then inside termux do `git clone https://github.com/emmaexe/anilist-notifications` then `cd anilist-notifications`
Then install [nodejs](https://wiki.termux.com/index.php?title=Node.js) and [n](https://www.npmjs.com/package/n) 
You can install n using `npm install -g n`
Then run `n 18` to install node.js version 18.x
Then run `npm i` in the root of the project to install nodejs modules.
Then run `node .` to start the server.

It should run in the background now and you should be able to do the setup instructions you can find in [README.md](https://github.com/emmaexe/anilist-notifications/blob/main/README.md)

If using the `n` command fails you can try to skip that part with `npm install n` and `n 18` but i don't know what version of node you will be running and it might not be supported, I am not sure.
